services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=postgres
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  krakend:
    image: krakend:latest
    ports:
      - "8081:8080"
    volumes:
      - ./krakend/krakend.json:/etc/krakend/krakend.json
    command: [ "run", "--config", "/etc/krakend/krakend.json" ]
    depends_on:
      - app

volumes:
  postgres_data:
  redis_data:
